Pin stable/queens to xenial nodeset
Bionic instances do not have nodejs 4. This patch pins stable/queens
to ubuntu-xenial nodes.

To resolve the following error:
apt.cache.FetchFailedException: W:The repository
'https://deb.nodesource.com/node_4.x bionic Release'
does not have a Release file.

Change-Id: I8cd1b22b636098bf26c880adce0ffb34f4ef79ae
(cherry picked from commit 353cc57d9be3f4aac6bc2adde70831f76da459f9)